### ISSUE TITLE
[Feature request] Fence texture fix, altered trapdoor recipe

### ISSUE THREAD

**Issue by Duranson1** [DanyGames2014/UniTweaks#19] opened 2024-12-26 10:06 UTC
Both a vanilla bug and present in unitweaks- connected fence underside texture is blank, is there a possible fix for this through unitweaks? Another feature request - would love if trapdoors could craft four, similar to the config option present for stairs crafting.

**Comment by DanyGames2014** [comment] 2024-12-27 07:46
Can you attach a screenshot of the missing texture?

**Comment by Duranson1** [comment] 2024-12-28 00:08
![image](https://github.com/user-attachments/assets/eea94728-9c5c-4535-a70b-85cf43bdd2f3)
Shown here, when fences are connected their underside is missing a texture

**Comment by telvarost** [comment] 2024-12-28 00:24
Ah, the texture is not missing. It is simply very dark. If you look at the fence posts higher up on the left in your photo, you can see the underside texture.

**Comment by DanyGames2014** [comment] 2024-12-28 07:35
Okay it seems like this is caused by the game taking the light level of the bottom face from the block below, which is correct for anything but blocks with a visible bottom face standing on another block. I will make a toggleable fix to allow for fences to take the bottom face brightness from their own block.
Also the adjustable trapdoor crafting size will be in recipes - tweaked

**Comment by DanyGames2014** [comment] 2024-12-28 09:16
Both requests implemented in UniTweaks 0.16.0 https://modrinth.com/mod/unitweaks/version/0.16.0
Closing the issue

**Closed by DanyGames2014** 2024-12-28 09:16 UTC

**Comment by Duranson1** [comment] 2024-12-28 09:59
Strangely still present in latest version for me. Updated and ensured is bugfix is enabled in config.
